# Generated by Django 3.2.21 on 2023-10-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardtyperef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardtype', models.IntegerField(db_column='CardType', unique=True)),
                ('cardtypedesc', models.CharField(db_column='CardTypeDesc', max_length=10)),
            ],
            options={
                'db_table': 'CardTypeRef',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registercard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardno', models.CharField(db_column='CardNo', max_length=20, unique=True)),
                ('cardid', models.CharField(blank=True, db_column='CardId', max_length=20, null=True)),
            ],
            options={
                'db_table': 'RegisterCard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dailybind',
            fields=[
                ('ProdId', models.CharField(db_column='ProdId', max_length=20)),
                ('ProdName', models.CharField(blank=True, db_column='ProdName', max_length=10000, null=True)),
                ('CardNo', models.IntegerField(db_column='CardNo')),
                ('CardType', models.IntegerField(db_column='CardType')),
                ('Spec', models.CharField(blank=True, db_column='Spec', max_length=50, null=True)),
                ('SpecSub', models.CharField(blank=True, db_column='SpecSub', max_length=50, null=True)),
                ('Price', models.IntegerField(db_column='Price')),
                ('Currency', models.CharField(db_column='Currency', max_length=10)),
                ('Qty', models.IntegerField(db_column='Qty')),
                ('LogDate', models.DateField(db_column='LogDate')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DailyBind',
            },
        ),
    ]
